[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-suse-linux-gcc"
runner = "/usr/riscv64-suse-linux/sys-root/lib/ld-linux-riscv64-lp64d.so.1 --library-path /usr/riscv64-suse-linux/sys-root/lib:/usr/riscv64-suse-linux/sys-root/lib64:/usr/riscv64-suse-linux/sys-root/lib64/lp64d:${sysroot}/usr/lib64/lp64d"
rustflags = ["-C", "target-feature=+b,+zca,+zcb,+zicond"]
rustdocflags = ["-C", "target-feature=+b,+zca,+zcb,+zicond"]
